import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import RootLayoutClient from "./RootLayoutClient";

const montserrat = Montserrat({
	variable: "--font-montserrat",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${montserrat.variable}  antialiased`}>
				<RootLayoutClient>{children}</RootLayoutClient>
			</body>
		</html>
	);
}
